2025-06-13 21:50:34.614 [lettuce-nioEventLoop-4-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:50:40.948 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:50:47.362 [lettuce-nioEventLoop-4-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:50:54.460 [lettuce-nioEventLoop-4-11] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:51:01.652 [lettuce-nioEventLoop-4-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:51:07.856 [lettuce-nioEventLoop-4-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:51:18.156 [lettuce-nioEventLoop-4-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:51:36.645 [lettuce-nioEventLoop-4-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:52:08.758 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:52:40.851 [lettuce-nioEventLoop-4-6] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:53:12.943 [lettuce-nioEventLoop-4-7] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:53:45.054 [lettuce-nioEventLoop-4-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:54:17.152 [lettuce-nioEventLoop-4-9] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:54:49.259 [lettuce-nioEventLoop-4-10] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:55:21.353 [lettuce-nioEventLoop-4-11] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:55:53.467 [lettuce-nioEventLoop-4-12] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:56:25.547 [lettuce-nioEventLoop-4-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:56:57.655 [lettuce-nioEventLoop-4-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:57:29.753 [lettuce-nioEventLoop-4-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:58:01.852 [lettuce-nioEventLoop-4-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
2025-06-13 21:58:33.955 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.231.128/<unresolved>:6379]: Connection refused: no further information: /192.168.231.128:6379
